riferrei/srclient

- schemaRegistryClient.go
Scheme type is not required to be part of request
Fixes https://github.com/riferrei/srclient/issues/11
> Scheme type is not required to be part of request

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
Add Reference type.
Add []Reference variadic argument to the CreateSchema api.
Add initial test cases for the SchemaRegistryClient.
CreateSchema should not break existing implementations due to the nature of the Go's varargs.
> Add references to the CreateSchema api

- schemaRegistryClient.go
- schemaRegistryClient_test.go
Revert PR #12 as `schemaType` is required for the latest API.
Add `schemaType` to the test suite.
Resolves #19
> Revert PR #12

- go.mod
- go.sum
- schemaRegistryClient.go
As per #32, an inner semaphore will stop the srclient from causing significant overhead with too many open files error.
Please review.
> Add Semaphore to HTTP Requests

- schemaRegistryClient.go
By setting default codecCreation to false we can have default support for protobuf. Also added Codec generation to schema.Codec() call to make up for this change, this way overall behaviour will stay the same for avro users. Fixes #30
> Enable Default Support for Protobuf

- schemaRegistryClient.go
- schemaRegistryClient_test.go
According to the schema registry API docs, we get a list of references when reading or creating a new schema.
Reference: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions
> Add references to Schema

- schemaRegistryClient.go
- schemaRegistryClient_test.go
This issue refers to the initial question : https://github.com/riferrei/srclient/issues/47
We are considering using this library in our producers however given the throughput we aim it feels not right to hit the schema registry on every call. 
This change aligns the behavior of the caching with the java implementation.
See: https://github.com/confluentinc/schema-registry/blob/8c4385c0f3b14bb5fb1046661f9bb5ff532de2d1/schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java#L202
Who wants to disable caching can do it via the `CacheEnabled(boolean)` method.
> Do not disable cache when fetching a schema

- mockSchemaRegistryClient.go
- mockSchemaRegistryClient_test.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
As per #31 and a short discussion on #47, this PR removes all IsKey arguments therefore making the arbitrary functions default and also exposes the http.Client for possible configurations for the developers.
Introduces breaking changes.
> Remove IsKeys and Arbitrary Functions, Expose Http Client

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
The confluent schema registry API has this endpoint:
```POST /subjects/(string: subject)```
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)
This is to check if a schema has already been registered under a specific subject.
This method is important because it is the schema lookup method that the serialiser is supposed to use if both "auto.register.schemas" and "use.latest.version" are set to false.
I also added test cases.
> Added LookupSchema method to SchemaRegistryClient

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
After caching, the schema in the cache does not change. If the latest schema changes on the schema registry, the new schema will not be retrieved. This reset mechanism allows retrieving the most updated version of the schema without the need to exit from application.
The cache could be reset periodically to retrieve the most updated version.
> Add reset cache mechanism to SchemaRegistryClient

- README.md
Apologies, there is a typo in the link to the go report badge in #61
The following PR corrects the typo.
> fix link to go report badge

- schemaRegistryClient.go
- schemaRegistryClient_test.go
In response to (#51), this PR adds `NewSchema` function proposed in the aforementioned ticket. 
This function clears the limitation blocking package from being mocked and tested with package such as `gomock`.
Comments are welcome.
> add NewSchema func (#51)

- mockSchemaRegistryClient.go
The current implementation of `MockSchemaRegistryClient` does not set schema type when calling `generateVersion`.
For this we are adding a schema type parameter to the `generateVersion` method and setting it on each new schema version.
> Setting schema type for mock client schemas

- schemaRegistryClient.go
This is needed to look up schemas that have `/` and probably other names in them.
This comes up when using Protos [1], as imports for schemas named like `google/protobuf/timestamp.proto` need to be resolved.
1. https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html#protobuf-serializer
> Url Encode the subject parameter

- mockSchemaRegistryClient.go
- mockSchemaRegistryClient_test.go
- schemaRegistryClient.go
The ability to remove specific version of the scheme is added according to [https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)) .
Can be useful for rolling back releases. 
Please review.
> Delete subject by version

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
The schema registry REST API allows you to specify references when doing [compatibility checks](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#sr-api-compatibility)
If you have a schema with references the current compatibility check without references will fail. This PR is adding in support for references for compatibility in the same way that it is supported for the other operations.
> add references to IsSchemaCompatible check

- schemaRegistryClient.go
- schemaRegistryClient_test.go
Older versions of the Confluent Schema Registry API don't support fields `schemaType` or `References`. Right now, this package always includes these in requests, even if they aren't being used. Since these fields were added to the API, the documentation has stated that they are optional fields. And it's documented that `schemaType` is always assumed to be Avro when it isn't specified. 
This PR ensures that these fields are only included in the request when they're not empty. And it does this with minimal changes to the package.
I need this behavior in order to use this package for my use case. And I've found a few previous issues that had problems that this PR would address:
https://github.com/riferrei/srclient/issues/11 https://github.com/riferrei/srclient/issues/19 …
> Only include schemaType and References when needed

- mockSchemaRegistryClient.go
- mockSchemaRegistryClient_test.go
- schemaRegistryClientIntegration_test.go
- schemaRegistryClient_test.go
Did a few. things, with the removal of the `else` being the main update.
- Make tests run in parallel
- Rename unexported mock properties to better reflect purpose (they aren't caches)
- Fix existing schemas not loading if a version is given in `SetSchema`
If you're not interested in the rename or parallel I can remove those changes
> Remove else statement that causes schemas to not be set correctly

- EXAMPLES_AVRO.md
- mockSchemaRegistryClient.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
This PR adds `NewSchemaRegistryClient` which sets default values and allows users to override specific values (such as the client, and not the semaphore weight). Aside from this, minor improvements in preallocating slices.
Related to #101
> Add preallocations, add constructor with fuctional options

- mockSchemaRegistryClient.go
- mockSchemaRegistryClient_test.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
This PR adds the method `GetSubjectVersionsById` that returns subject-version pairs identified by the schema ID.
> Add GetSubjectVersionsById method

- schemaRegistryClient.go
This adds a check for confluent.cloud that changes authentication to match the requested "basic" header.
> Add support for confluent.cloud bearer token authentication

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
- schemaRegistryClient_test.go
GetSchemaRegistryURL returns the URL of the Schema Registry
> feat(url): Add new function `GetSchemaRegistryURL`

- mockSchemaRegistryClient.go
- schemaRegistryClient.go
This function already exists : func (client *SchemaRegistryClient) CodecJsonEnabled(value bool) but is currently not exposed in the interface
> feat(json): Add function `CodecJsonEnabled` inside ISchemaRegistryClient interface

- go.mod
- go.sum
- mockSchemaRegistryClient.go
- mockSchemaRegistryClient_test.go
- Add support for codecJsonEnabled in mock
- Also upgrade goavro library
Fixes: #116
> Add support for codecJsonEnabled in mock

- schemaRegistryClient.go
Why?
There is a bug detected when, for example, a subject contains space characters.
The package currently uses `+` to encode space in path instead of `%20`.
There might be other encoding issues I'm not aware of.
What?
I search through code for usage of `httpRequest` and reviewed all calls to make sure they use url.PathEscape when encoding path parameters.
Some were using url.QueryEscape. Some had no escaping.
Addresses:
https://github.com/riferrei/srclient/issues/113
> bugfix: Use url.PathEscape for path arguments
